apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: node-feature-discovery

resources:
- ../../base/rbac
- ../../base/nfd-crds
- ../../base/master
- ../../base/worker-daemonset
- ../../base/gc
- ../../base/topologyupdater-daemonset
- ../../base/rbac-topologyupdater
- namespace.yaml

components:
- ../../components/worker-config
- ../../components/common
- ../../components/master-config
- ../../components/topology-updater
- ../../components/topology-updater-config

